### ISSUE TITLE
Encoder Broken - Stack Overflow Error

### ISSUE THREAD

**Issue by kosinix** [PistonDevelopers/image-png#51]
Im getting a thread 'main' has overflowed its stack error. Just use the sample code in docs.rs to reproduce the bug:

```
    // For reading and opening files
    use std::path::Path;
    use std::fs::File;
    use std::io::BufWriter;
    // To use encoder.set()
    use png::HasParameters;

    let path = Path::new(r"/path/to/image.png");
    let file = File::create(path).unwrap();
    let ref mut w = BufWriter::new(file);

    let mut encoder = png::Encoder::new(w, 2, 1); // Width is 2 pixels and height is 1.
    encoder.set(png::ColorType::RGBA).set(png::BitDepth::Eight);
     let mut writer = encoder.write_header().unwrap();

    let data = [255, 0, 0, 255, 0, 0, 0, 255]; // An array containing a RGBA sequence. First pixel is red and second pixel is black.
    writer.write_image_data(&data).unwrap(); // Save
```

This works in 0.5.2 but not on 0.6.1. (btw Also getting blank jpegs for image 0.12.0 (no prob on 0.10.4) that might be related but i'm too tired for today to investigate and file an issue.)

**Comment by oyvindln** [comment]
I can reproduce this on windows(32-bit) in debug mode, in release mode it seems to run fine. I'm getting overflows when running the tests in deflate too, so I suspect the problem is in the deflate crate, and that it gets optimised out in release mode. On Ubuntu (64-bit) it doesn't happen so I guess there is some differences in stack sizes.

I will have a look at the deflate code again to see if there are any places where stack usage could be reduced.

**Comment by oyvindln** [comment]
Okay, I think I solved the issue for now. Rustc doesn't seem to optimise Box::new(<large struct>) in debug mode, so I boxed the underlying buffers as well for now, and I no longer get stack overflows. The updates are published in deflate 0.7.2.

**Comment by nwin** [comment]
That is a know like limitation of Rust which will be solved when the box-Syntax becomes stable. I don't see any need to fix that now.

**Comment by nwin** [comment]
Ok, I bumped the version of png an will publish it soon. @oyvindln thanks for fixing that!
